name = "viva-impact-pages"
pages_build_output_dir = "apps/web/build"

[[d1_databases]]
binding = "DB"
database_name = "viva-impact-db"
database_id = "00000000-0000-0000-0000-000000000000"

[vars]
# Google OAuth client id used for verifying ID-tokens from the frontend
GOOGLE_CLIENT_ID = ""
# Optional overrides for auth behaviour
ADMIN_ROLE_NAME = "admin"
SESSION_COOKIE_NAME = "viva_session"
SESSION_TTL_SECONDS = "604800"
