name = "viva-impact-api"
compatibility_date = "2024-12-01"

# Runtime bindings for Pages Functions / Workers
[[d1_databases]]
binding = "DB"
database_name = "viva-impact-auth"
# Replace with the production database id via deployment automation
database_id = "00000000-0000-0000-0000-000000000000"

[[kv_namespaces]]
binding = "SESSION_CACHE"
# Replace with the production namespace id via deployment automation
id = "00000000000000000000000000000000"
preview_id = "11111111111111111111111111111111"

[vars]
SESSION_COOKIE_NAME = "viva_session"
SESSION_TTL_SECONDS = "604800" # 7 days

# Secrets (configure via `wrangler secret put` or Pages project settings):
# - TURNSTILE_SECRET_KEY
