name: Lockfile Sync (auto-commit)

on:
  workflow_dispatch:
  push:
    branches: [ feature-login-vite ]   # ändra till den gren Cloudflare bygger

permissions:
  contents: write

env:
  NODE_VERSION: "22"

jobs:
  sync-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      # Uppdatera lockfilen för hela monorepot (workspaces-aware)
      - name: Install (update lockfile)
        run: npm install --no-fund --no-audit

      # (valfritt) sanity check
      - name: Verify vite deps present
        run: |
          npm ls vite @vitejs/plugin-react || true
          npm ls -w @viva/web postcss || true

      # Commit & push om något ändrats (t.ex. package-lock.json)
      - name: Commit lockfile if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: sync package-lock.json for Vite"
          branch: ${{ github.ref_name }}
